### ISSUE TITLE
Version for 1.16.5

### ISSUE THREAD

**Issue by Silverminer007** [Zarathul/simpleportals#13]
Hello. 
I'm a minecraft mod developer and love your mod! I saw, there were only versions up to 1.15.2 but i would love to see your mod on 1.16.5. In an other issue, i saw you've mententioned a port to 1.16, but that was 1 year ago. Are you still working on the port?

If not i would love to port your mod myself, but wanted to ask before doing and you don't like. If you don't matter i would also publish your mod on my curseforge (Surly i would give you the credits)

Sorry for this complacted way of comunication, but i havn't found another way to ask.
Here a link to my curseforge: https://www.curseforge.com/members/silverminer007/projects

Sorry for bothering you, i hope i havn't missed anything

Have a nice day!

**Comment by Zarathul** [comment]
Well, actually there is a [1.16 version](https://github.com/Zarathul/simpleportals_fabric) but it's for Fabric not Forge. At some point Forge annoyed me so much that I decided to switch APIs. With that said, the chance that I'll touch Forge again is very low.

If you really want to, you can of course do your own port. The license I choose allows for that, thanks for asking though! If you decide to release your version on Curseforge or wherever, the only thing I would ask of you is to slightly change the name of the mod. Add a "Reloaded" or something to the name, so people can differentiate your version from mine. Otherwise you are good to go.

**Comment by Silverminer007** [comment]
Thanks a lot. I saw the version for Fabric, but I'm coding and playing on Forge. I've started to port your mod and I'm quite done. Of course i'll change the name of the mod and the modid too. When i publish, i'll send a link to the site and you can say whether it's okay or not.
Have a nice day!

**Comment by Silverminer007** [comment]
I've created the curseforge project and it only needs validation my an moderator to upload. Here's the link: https://www.curseforge.com/minecraft/mc-mods/simpleportals-reloaded-forge
Please say if something isn't okay and/or should be changed. You've done grate work with this mod!
I'm gonna close this issue because the Problem is cleared yet, or not?

**Comment by Zarathul** [comment]
Had a quick look at it, everything seems fine by me. You are good to go :).
