### ISSUE TITLE
Portal Direction changing after server reboot

### ISSUE THREAD

**Issue by TeknoRapture** [Zarathul/simpleportals#8]
After a server reboot the direction the player leaves the portal sometimes changes so that the player  is facing the wrong way after going through the portal.

Make a portal and connect it in the same dimension.  When you go through it you will be facing the correct direction on the other side.  After a SSP "server" restart, after going through a portal sometimes the player is facing the wrong direction.  I'm pretty sure this happens when the exit portal is facing a different direction than entry portal.  The portal I made to the Nether is correct when going Nether -> Other Dimension, but wrong after reboot for Other Dimension -> Nether.

The rotational data is probably not being written to disk and/or not being loaded after a reboot.

Mine and my son's bases use the portals integrated directly into the Architecture with the bases spread across 10 or more dimensions.  ie a quarry room in the nether connected to the ore processing room in the Deep Dark, which has a portal to the workshop in the overworld, etc etc. It was perfect when set up, movement between "rooms" was as expected.  After reboot it was such a disappointment and very confusing while walking through the base to be facing in the wrong direction most of the time.

Thanks!

**Comment by Zarathul** [comment]
I remember some problems with player facing after teleportation in multiplayer. The restarting should have nothing to do with it, though. Last time I couldn't fix it, but I'll take another look at it.

**Comment by Zarathul** [comment]
**Short version:** Install https://www.curseforge.com/minecraft/mc-mods/gotta-go-fast either on the dedicated server or on the client that hosts the multiplayer game and everything should work as expected. It is a coremod (not made by me) so be warned, they can always cause issues, but with over half a million downloads it should be fine.

**Note about the spawning mechanics**
Where a player is placed after being teleported is determined every time right before the teleportation (nothing is saved). Basically there has to be enough room for the player one block in front or behind the portal (above or below if the portal is horizontal). If the portal is free standing, in the middle of a room or something, the order in which the portal looks for a place to put the player is south before north and east before west. So if you want to come out of a portal facing north for example you have to block off the south side, or build the portal against a wall. Also the player always is placed facing away from the portal (or should be if it wasn't for the bug described below).

**So what about the bug and why install another mod to fix it?!**
The vanilla minecraft server code has some very basic, borderline stupid, anti speed hacking checks in it, that get triggered by teleportations. This is the cause for the "Player moved too quickly!" log messages you might have seen and the problems with the player facing direction. The only way to fix this is a coremod that changes minecraft server code which is relatively complicated and generally frowned upon because it can cause all kinds of issues with other mods. Therefore I'm not gonna do it, but luckily someone else already has. The aforementioned "Gotto-Go-Fast" mod does exactly what it needs to do, disable the speed check.

**Comment by Zarathul** [comment]
I assume this is solved. If not, feel free to leave another comment.

**Comment by TeknoRapture** [comment]
OOPS!

I'm sorry I didn't respond, I was in the woods volunteering at a summer
camp.  Thanks for the prompt response!  I'll try to throw you some cash
when I can!

-Tekno
